### ISSUE TITLE
Code cleanup for 2.0 release

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#559]
This issue collects changes to consider for the next major release.

Issues will be made for any changes that we commit to.

Ideas:
- [ ] ~Investigate whether intervalmapper, transcriptmapper, and variantmapper are obsolete~.
- [ ] move models to hgvs.models.*. (#583)
- [ ] make seqrepo dependency optional
- [ ] cleanup hgvs.easy
- [ ] remove six
- [ ] ~remove __future__ imports~ (#688)
- [ ] code reformat
- [ ] code restructure (src/, setup.cfg)
- [ ] verify that all dependencies are up-to-date. e.g., see #584 
- [ ] improve consistency of error handling, esp. returning variant as-is v. exceptions when error is encountered (code currently does both)

External needs:
- [ ] SeqRepo raises error when coordinates are out-of-bounds
- [ ] SeqRepo make metadata accessible

**Comment by reece** [comment]
Tracking is now in [the 2.0 milestone](https://github.com/biocommons/hgvs/milestone/11)
